AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - config/initializers/devise.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
